services:
  dev:
    image: v2x-ros-driver:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        DOCKER_ORG: usdotfhwastoldev
        DOCKER_TAG: develop-humble
        GIT_BRANCH: develop
    volumes:
      - ./v2x_ros_driver:/home/carma/src/v2x_ros_driver
      - ${HOME}/.claude:/home/carma/.claude
      - vscode-server:/home/carma/.vscode-server
      - vscode:/home/carma/src/v2x_ros_driver/.vscode
    stdin_open: true
    tty: true

volumes:
  vscode-server:
  vscode:
